spring.application.name=notebook
server.port=8080
notebook.notes-dir=${user.home}/notebook/notes
notebook.cors-allowed-origins=http://localhost:5173
notebook.cors-allowed-methods=GET,POST,PUT,DELETE,OPTIONS
notebook.cors-allowed-headers=*
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
