# server properties
server.port=8080

# spring properties
spring.application.name=notebook
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# spring ai
spring.ai.mcp.server.enabled=true
spring.ai.mcp.server.protocol=STREAMABLE
spring.ai.mcp.server.name=notebook-mcp-server
spring.ai.mcp.server.version=@project.version@
spring.ai.mcp.server.streamable-http.mcp-endpoint=/mcp
spring.ai.mcp.server.annotation-scanner.enabled=true

# note book application properties
notebook.notes-dir=${user.home}/notebook/notes
notebook.cors-allowed-origins=http://localhost:5173
notebook.cors-allowed-methods=GET,POST,PUT,DELETE,OPTIONS
notebook.cors-allowed-headers=*